import greentea from "../assets/image/green-tea.png";
import Adoramyo from "../assets/image/Adoramyo.png";
import dmannos from "../assets/image/dmannos.png";
import myKind from "../assets/image/myKind-adrenal.png";
import inositol from "../assets/image/jf-inositol-.png";
import pancreatin from "../assets/image/pancreatin-.png";
import uva from "../assets/image/strawberry-cream.png";
import strawberry from "../assets/image/uva-ursi.png";
import idole from "../assets/image/idole.png";
import Bronson from "../assets/image/Bronson-k2d3.png";
import chlorophyll from "../assets/image/chlorophyll-mint.png";
import gol from "../assets/image/gol-once-women.png";
import hyponidd2x from "../assets/image/hyponidd2x.png";
import raspberry from "../assets/image/raspberry-leaf-tea.png";
import dim3001 from "../assets/image/dim3001.png";
import msmpwd from "../assets/image/msmpwd.png";
import iced from "../assets/image/iced-coffee.png";
import spearmint from "../assets/image/spearmint-tea.png";
export const healthGoal = [
  "Active Livestyle",
  "Bload Suger Support",
  "Bone Health",
  "Brain Health",
  "Diet & LifeStyle",
  "Detoxification",
  "Digestive Health",
  "Energy Support",
  "Eye Health",
  "Immune Support",
  "Joint Supporst",
  "Sleep & Relaxation",
  "Respiratory Support",
  "Sexual Health & Fertility",
  "Men's Health",
  "Women's Health",
];

export const navBar = [
  "Vitamins & Supplements",
  "Herbs",
  " Minerals",
  "Food & Grocery",
  " Beauty & Personal Care",
  "Protein & Fitness",
  " Clearance",
];

export const shopCategory = [
  "Aromatherapy",
  "Beauty & Personal ",
  "Clearance",
  "Food & Grocery ",
  "Health Goal",
  "Active Lifestyle ",
  "Blood Sugar Support ",
  "Bone Health ",
  "Brain Health",
  "Detoxification ",
  "Diet & Lifestyle ",
  "Digestive Health",
  "Energy Support",
  "Eye Health",
  " Heart Health",
  "Immune Support ",
  "Joint Health",
  "Joint Support ",
  "Men's Health ",
  "Mens Health ",
  "Respiratory Support ",
  "Sexual Health & Fertility",
  "Sleep & Relaxation",
  "Women's Health",
  "Women's Health ",
  "Herbs",
  "Minerals",
  "Protein & Fitness",
  "Vitamins & Supplements",
];
export const productSample = [
  {
    _id: 1,
    name: "product1",
    desc: "NOW Foods EGCg Green...",
    price: 22000.0,
    discount: 6,
    img: greentea,
    quantity: 1,
  },

  {
    _id: 2,
    name: "product2",
    desc: "Adoramyo",
    price: 16000.0,
    discount: 7,
    img: Adoramyo,
    quantity: 1,
  },
  {
    _id: 3,
    name: "product3",
    desc: "Adoramyo",
    price: 16000.0,
    discount: 7,
    img: Adoramyo,
    quantity: 1,
  },
  {
    _id: 4,
    name: "product4",
    desc: "dmannos",
    price: 25000.0,
    discount: 8,
    img: dmannos,
    quantity: 1,
  },
  {
    _id: 5,
    name: "product5",
    desc: "Garden of Life mykind ...",
    price: 25000.0,
    discount: 10,
    img: myKind,
    quantity: 1,
  },
  {
    _id: 6,
    name: "product6",
    desc: "Jarrow Formulas Myo Inosi...",
    price: 25000.0,
    discount: 2,
    img: inositol,
    quantity: 1,
  },
  {
    _id: 7,
    name: "product7",
    desc: "pancreatin-",
    price: 35000.0,
    discount: 7,
    img: pancreatin,
    quantity: 1,
  },
  {
    _id: 8,
    name: "product8",
    desc: "strawberry",
    price: 24000.0,
    discount: 5,
    img: strawberry,
    quantity: 1,
  },
  {
    _id: 9,
    name: "product9",
    desc: "Nature’s Way Uva Ursi Le...",
    price: 24000.0,
    discount: 5,
    img: uva,
    quantity: 1,
  },
  {
    _id: 10,
    name: "product10",
    desc: "idole",
    price: 16000.0,
    discount: 4,
    img: idole,
    quantity: 1,
  },
  {
    _id: 11,
    name: "product11",
    desc: "Bronson-k2d3",
    price: 17000.0,
    discount: 6,
    img: Bronson,
    quantity: 1,
  },
  {
    _id: 12,
    name: "product12",
    desc: "chlorophyll-mint",
    price: 17000.0,
    discount: 3,
    img: chlorophyll,
    quantity: 1,
  },
  {
    _id: 13,
    name: "product13",
    desc: "gol-once-women..",
    price: 25000.0,
    discount: 5,
    img: gol,
    quantity: 1,
  },
  {
    _id: 14,
    name: "product14",
    desc: "hyponidd2x",
    price: 46000.0,
    discount: 2,
    img: hyponidd2x,
    quantity: 1,
  },
  {
    _id: 15,
    name: "product15",
    desc: "raspberry-leaf-tea..",
    price: 25000.0,
    discount: 4,
    img: raspberry,
    quantity: 1,
  },
  {
    _id: 16,
    name: "product16",
    desc: "dim3001...",
    price: 19000.0,
    discount: 3,
    img: dim3001,
    quantity: 1,
  },
  {
    _id: 17,
    name: "product17",
    desc: "msmpwd...",
    price: 10000.0,
    discount: 2,
    img: msmpwd,
    quantity: 1,
  },
  {
    _id: 18,
    name: "product18",
    desc: "iced-coffee...",
    price: 10000.0,
    discount: 2,
    img: iced,
    quantity: 1,
  },
  {
    _id: 19,
    name: "product19",
    desc: "spearmint-tea...",
    price: 10000.0,
    discount: 2,
    img: spearmint,
    quantity: 1,
  },
];
